version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: qa_local_pg
    environment:
      POSTGRES_USER: qa_user
      POSTGRES_PASSWORD: qa_pass
      POSTGRES_DB: qa_framework
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U qa_user"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  pgdata:



